# Generated by Django 4.2.15 on 2024-08-29 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=200)),
                ('store_email', models.CharField(max_length=200)),
                ('store_words', models.CharField(max_length=200)),
            ],
        ),
    ]
